version: 0.0
os: Linux
files:
  - source: index.html
    destination: /var/www/html/
files_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root