version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Specify the runtime version for your application
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running pre-build steps...
      - npm run lint
      - npm test

  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Preparing artifacts...
      - zip -r build.zip .
      - echo Build artifacts prepared.

artifacts:
  files:
    - build.zip
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
