bases:
- ../blue-green-repo/deployment/blue
- ../blue-green-repo/deployment/green
- ../blue-green-repo/service/
resources:
    - namespace.yaml
    - ingresscontrol.yaml
    - ingresscontrolstage.yaml
